import { Inter } from "next/font/google";
import "./globals.css";
import Button from "./page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <Button/>
  );
}
